/**
 * deno run -A scripts/install_linux.ts <install|uninstall> [flags]
 *
 * Per-user install (no sudo) of the `deno desktop` build into ~/.local:
 * app copy, launcher with log file, menu entry + icon, autostart, `deno-asr` on PATH.
 * Config and dataset are never touched.
 */
import { dirname, join } from "@std/path";
import { buildLinux } from "./build.ts";
import { configDir } from "../src/core/config.ts";
import { sendControl, socketPath } from "../src/core/control.ts";
import { isWayland } from "../src/core/platform/linux.ts";
import { appIcon } from "../src/desktop/icons.ts";

const ROOT = new URL("..", import.meta.url).pathname;
const DIST = join(ROOT, "dist/deno-asr");
export const APP_ID = "dev.damian.deno-asr";

export interface InstallPaths {
  /** Holds `app/` and the launcher script. */
  dataDir: string;
  appDir: string;
  appNew: string;
  appOld: string;
  exe: string;
  launcher: string;
  bin: string;
  desktop: string;
  autostart: string;
  icon: string;
  stateDir: string;
  log: string;
}

type Env = Pick<typeof Deno.env, "get">;

export function installPaths(home: string, env: Env = { get: () => undefined }): InstallPaths {
  const data = env.get("XDG_DATA_HOME") || join(home, ".local/share");
  const config = env.get("XDG_CONFIG_HOME") || join(home, ".config");
  const state = env.get("XDG_STATE_HOME") || join(home, ".local/state");
  const dataDir = join(data, "deno-asr");
  const appDir = join(dataDir, "app");
  const stateDir = join(state, "deno-asr");
  return {
    dataDir,
    appDir,
    appNew: `${appDir}.new`,
    appOld: `${appDir}.old`,
    exe: join(appDir, "deno-asr"),
    launcher: join(dataDir, "deno-asr-launch"),
    bin: join(home, ".local/bin/deno-asr"),
    desktop: join(data, "applications", `${APP_ID}.desktop`),
    autostart: join(config, "autostart", `${APP_ID}.desktop`),
    icon: join(data, "icons/hicolor/256x256/apps", `${APP_ID}.png`),
    stateDir,
    log: join(stateDir, "app.log"),
  };
}

/** POSIX shell single-quoting. */
export function shq(s: string): string {
  return `'${s.replaceAll("'", `'\\''`)}'`;
}

/** Launcher run by the menu entry: GNOME discards app output, so send it to a log file. */
export function launcherScript(p: InstallPaths, debug: boolean): string {
  return [
    "#!/bin/sh",
    "# Generated by scripts/install_linux.ts. Re-run the installer instead of editing.",
    `mkdir -p ${shq(p.stateDir)}`,
    ...(debug ? ["export ASR_DEBUG='*'"] : []),
    `printf '\\n=== %s start ===\\n' "$(date -Is)" >>${shq(p.log)}`,
    `exec ${shq(p.exe)} "$@" >>${shq(p.log)} 2>&1`,
    "",
  ].join("\n");
}

/** Quotes an Exec argument per the Desktop Entry spec (quoting + string-value escaping). */
export function desktopExecArg(arg: string): string {
  if (!/[\s"'\\$`<>~|&;*?#()%]/.test(arg)) return arg;
  const quoted = arg.replace(/[\\"`$]/g, "\\$&").replaceAll("%", "%%");
  // Desktop string values unescape `\\` once more, so double every backslash.
  return `"${quoted.replaceAll("\\", "\\\\")}"`;
}

export function desktopEntry(opts: { launcher: string; autostart: boolean }): string {
  const lines = [
    "[Desktop Entry]",
    "Type=Application",
    "Name=Deno ASR",
    "Comment=Dictado por voz con atajo global",
    `Exec=${desktopExecArg(opts.launcher)}`,
    `Icon=${APP_ID}`,
    `StartupWMClass=${APP_ID}`,
    "Categories=Utility;",
    "Terminal=false",
  ];
  if (opts.autostart) {
    // Give the AppIndicator extension time to load, or the tray icon can't be created.
    lines.push("X-GNOME-Autostart-enabled=true", "X-GNOME-Autostart-Delay=5");
  }
  return lines.join("\n") + "\n";
}

export const REQUIRED_PACKAGES = [
  "xclip",
  "xdotool",
  "wl-clipboard",
  "zenity",
  "libnotify-bin",
  "netcat-openbsd",
  "libwebkit2gtk-4.1-0",
  "libayatana-appindicator3-1",
];
export const TRAY_EXTENSION = "gnome-shell-extension-appindicator";

/** `statusOf(pkg)` returns dpkg's status string, or null if unknown. */
export async function missingPackages(
  statusOf: (pkg: string) => Promise<string | null>,
  wayland: boolean,
): Promise<{ missing: string[]; trayExtension: boolean }> {
  const installed = async (pkg: string) => (await statusOf(pkg))?.includes("ok installed") ?? false;
  const wanted = wayland ? [...REQUIRED_PACKAGES, "ydotool"] : REQUIRED_PACKAGES;
  const missing: string[] = [];
  for (const pkg of wanted) if (!(await installed(pkg))) missing.push(pkg);
  return { missing, trayExtension: await installed(TRAY_EXTENSION) };
}

// ---------------------------------------------------------------------------

async function cmd(
  command: string,
  args: string[],
): Promise<{ code: number; stdout: string } | null> {
  try {
    const out = await new Deno.Command(command, {
      args,
      stdin: "null",
      stdout: "piped",
      stderr: "null",
    }).output();
    return { code: out.code, stdout: new TextDecoder().decode(out.stdout) };
  } catch {
    return null; // command not installed
  }
}

async function dpkgStatus(pkg: string): Promise<string | null> {
  const res = await cmd("dpkg-query", ["-W", "-f=${Status}", pkg]);
  return res && res.code === 0 ? res.stdout : null;
}

const exists = (p: string) => Deno.lstat(p).then(() => true, () => false);
const rmrf = (p: string) => Deno.remove(p, { recursive: true }).catch(() => {});

async function copyDir(from: string, to: string) {
  await Deno.mkdir(to, { recursive: true });
  for await (const e of Deno.readDir(from)) {
    const src = join(from, e.name);
    const dst = join(to, e.name);
    if (e.isDirectory) await copyDir(src, dst);
    else if (e.isFile) {
      await Deno.copyFile(src, dst);
      const { mode } = await Deno.stat(src);
      if (mode !== null) await Deno.chmod(dst, mode & 0o777);
    }
  }
}

async function writeFile(path: string, data: string | Uint8Array, mode = 0o644) {
  await Deno.mkdir(dirname(path), { recursive: true });
  if (typeof data === "string") await Deno.writeTextFile(path, data);
  else await Deno.writeFile(path, data);
  await Deno.chmod(path, mode);
  console.log(`+ ${path}`);
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** Kills every process running from the installed app dir (app + its asr-helper). */
async function stopInstalled(p: InstallPaths) {
  const pattern = `${escapeRegex(p.appDir)}/`;
  const running = await cmd("pgrep", ["-f", pattern]);
  if (!running || running.code !== 0) return;
  console.log("· parando la instancia instalada…");
  await cmd("pkill", ["-TERM", "-f", pattern]);
  for (let i = 0; i < 30; i++) {
    await new Promise((r) => setTimeout(r, 100));
    const still = await cmd("pgrep", ["-f", pattern]);
    if (!still || still.code !== 0) return;
  }
  // A frozen event loop never runs the SIGTERM handler.
  await cmd("pkill", ["-KILL", "-f", pattern]);
}

async function controlStatus(timeoutMs = 1_000): Promise<string | null> {
  return await Promise.race([
    sendControl("status").catch(() => null),
    new Promise<null>((r) => setTimeout(() => r(null), timeoutMs)),
  ]);
}

async function refreshCaches(p: InstallPaths) {
  await cmd("update-desktop-database", [dirname(p.desktop)]);
  await cmd("gtk-update-icon-cache", ["-f", "-t", join(dirname(p.icon), "../..")]);
}

interface InstallFlags {
  build: boolean;
  autostart: boolean;
  launch: boolean;
  debug: boolean;
}

async function install(p: InstallPaths, flags: InstallFlags) {
  // 1. Dependencies (report only; never runs sudo).
  const deps = await missingPackages(dpkgStatus, isWayland());
  if (deps.missing.length) {
    console.warn(`! faltan paquetes: sudo apt install ${deps.missing.join(" ")}`);
  }
  if (!deps.trayExtension) {
    console.warn(
      `! sin ${TRAY_EXTENSION} GNOME no muestra el icono de bandeja: sudo apt install ${TRAY_EXTENSION}`,
    );
  }

  // 2. Build.
  if (flags.build) {
    const owner = await Deno.stat(join(ROOT, "dist")).then((s) => s.uid, () => null);
    if (owner !== null && owner !== Deno.uid()) {
      throw new Error(
        `dist/ no es tuyo (uid ${owner}), seguramente de un build con sudo: sudo rm -rf ${
          join(ROOT, "dist")
        }`,
      );
    }
    await buildLinux();
  }
  if (!(await exists(join(DIST, "deno-asr"))) || !(await exists(join(DIST, "asr-helper")))) {
    throw new Error(`no hay build en ${DIST}: ejecuta sin --no-build o 'deno task build:linux'`);
  }

  // 3. Stop the installed copy (overwriting a mapped .so crashes it).
  await stopInstalled(p);
  const other = await controlStatus();
  if (other !== null) {
    console.warn(
      `! hay otra instancia respondiendo en ${socketPath()} (¿deno task dev?): la instalada ` +
        "no arrancará hasta que la cierres",
    );
  }

  // 4. Copy to app.new, then swap directories.
  await rmrf(p.appNew);
  await copyDir(DIST, p.appNew);
  await Deno.chmod(join(p.appNew, "deno-asr"), 0o755);
  await Deno.chmod(join(p.appNew, "asr-helper"), 0o755);
  await rmrf(p.appOld);
  if (await exists(p.appDir)) await Deno.rename(p.appDir, p.appOld);
  await Deno.rename(p.appNew, p.appDir);
  await rmrf(p.appOld);
  console.log(`+ ${p.appDir}/`);

  // 5. Integration.
  await writeFile(p.launcher, launcherScript(p, flags.debug), 0o755);
  await writeFile(p.icon, await appIcon(256));
  await writeFile(p.desktop, desktopEntry({ launcher: p.launcher, autostart: false }));
  if (flags.autostart) {
    await writeFile(p.autostart, desktopEntry({ launcher: p.launcher, autostart: true }));
  } else if (await exists(p.autostart)) {
    await Deno.remove(p.autostart);
    console.log(`- ${p.autostart}`);
  }
  await Deno.mkdir(dirname(p.bin), { recursive: true });
  if (await exists(p.bin)) await Deno.remove(p.bin);
  await Deno.symlink(p.exe, p.bin);
  console.log(`+ ${p.bin} -> ${p.exe}`);
  await refreshCaches(p);

  // 6. Launch.
  let launched = "";
  if (flags.launch && other === null) {
    // No pipes: the detached app must not hold any of our fds open.
    const code = await new Deno.Command("setsid", {
      args: ["-f", p.launcher],
      stdin: "null",
      stdout: "null",
      stderr: "null",
    }).spawn().status.then((s) => s.code, () => -1);
    if (code !== 0) {
      console.warn("! no se pudo lanzar la app; ábrela desde Actividades");
    } else {
      for (let i = 0; i < 40 && !launched; i++) {
        await new Promise((r) => setTimeout(r, 250));
        launched = (await controlStatus(500)) ?? "";
      }
      console.log(
        launched ? `✓ en marcha (estado: ${launched})` : `! no responde tras 10 s; mira ${p.log}`,
      );
    }
  }

  // 7. Summary.
  const onPath = (Deno.env.get("PATH") ?? "").split(":").includes(dirname(p.bin));
  console.log(`
✓ Deno ASR instalado
  app:        ${p.appDir}
  menú:       ${p.desktop}
  autostart:  ${flags.autostart ? p.autostart : "desactivado"}
  comando:    ${p.bin}${onPath ? "" : `  (${dirname(p.bin)} no está en tu PATH)`}
  log:        ${p.log}${flags.debug ? "  (con ASR_DEBUG=*)" : ""}
  config:     ${join(configDir(), "config.json")}

Arrancada desde el menú o el autostart, la app NO hereda las variables de tu shell
(DASHSCOPE_API_KEY, ELEVENLABS_API_KEY, HOTKEY…): guarda las API keys en Ajustes.`);
}

async function uninstall(p: InstallPaths) {
  await stopInstalled(p);
  for (const f of [p.desktop, p.autostart, p.icon, p.bin, p.launcher]) {
    if (await exists(f)) {
      await Deno.remove(f);
      console.log(`- ${f}`);
    }
  }
  for (const d of [p.appDir, p.appNew, p.appOld]) {
    if (await exists(d)) {
      await rmrf(d);
      console.log(`- ${d}/`);
    }
  }
  await Deno.remove(p.dataDir).catch(() => {}); // only if empty
  await refreshCaches(p);
  console.log(`
✓ Deno ASR desinstalado. Se conservan (bórralos a mano si quieres):
  config:  ${join(configDir(), "config.json")}
  log:     ${p.log}
  dataset: el directorio "datasetDir" de config.json (por defecto ~/deno-asr-dataset)`);
}

const USAGE = `uso: deno run -A scripts/install_linux.ts <install|uninstall> [flags]

install:
  --no-build      usa dist/deno-asr tal cual
  --no-autostart  no arrancar al iniciar sesión
  --no-launch     no arrancar la app al terminar
  --debug         la app instalada arranca con ASR_DEBUG=*`;

export function parseInstallFlags(args: string[]): InstallFlags {
  const flags: InstallFlags = { build: true, autostart: true, launch: true, debug: false };
  for (const a of args) {
    switch (a) {
      case "--no-build":
        flags.build = false;
        break;
      case "--no-autostart":
        flags.autostart = false;
        break;
      case "--no-launch":
        flags.launch = false;
        break;
      case "--debug":
        flags.debug = true;
        break;
      default:
        throw new Error(`flag desconocido: ${a}\n\n${USAGE}`);
    }
  }
  return flags;
}

if (import.meta.main) {
  if (Deno.build.os !== "linux") {
    console.error("install_linux.ts solo funciona en Linux");
    Deno.exit(1);
  }
  const home = Deno.env.get("HOME");
  if (!home) {
    console.error("HOME no está definido");
    Deno.exit(1);
  }
  const paths = installPaths(home, Deno.env);
  const [command, ...rest] = Deno.args;
  try {
    switch (command) {
      case "install":
        await install(paths, parseInstallFlags(rest));
        break;
      case "uninstall":
        await uninstall(paths);
        break;
      default:
        console.error(USAGE);
        Deno.exit(64);
    }
  } catch (err) {
    console.error(`✗ ${err instanceof Error ? err.message : err}`);
    Deno.exit(1);
  }
  // sendControl may leave a socket open on a frozen instance.
  Deno.exit(0);
}
